### ISSUE TITLE
where are the detail descriptions about generate features and train the cart forest？

### ISSUE THREAD

**Issue by GarrickLin** [luoyetx/JDA#3]
I read your code in CART part, but I can't find the detail descriptions in the paper. What references does it cite? In another word, which paper make you directly know the detail about the feature generation and training of CART?

**Comment by luoyetx** [comment]
1. for feature generation, the paper already has a detailed description, 3 scaled images with random offset to 2 landmarks. I scaled the offset not the image, but we can change it later. Shape-index feature is used to calculate the feature value, shape-index feature is well used for face alignment.
2. for training CART, because I used to implement a C++ version of face alignment in 3000 fps, the code is not open source, may share it later, I refer to 2 other repos [yulequan/face-alignment-in-3000fps](https://github.com/yulequan/face-alignment-in-3000fps) and [jwyang/face-alignment](https://github.com/jwyang/face-alignment) for 3000fps. CART needs classification and regression, 3000fps only needs regression, but classification is easier than regression, the paper says use maximum binary entropy reduction to select a feature for classification, where regression use maximum variance reduction. For more information about how to train CART, you can google some blogs.

I suggest you may refer to the paper [Face Alignment at 3000 FPS via Regressing Local Binary Features](http://research.microsoft.com/en-US/people/yichenw/cvpr14_facealignment.pdf).
